FROM golang:1.24.4-alpine3.22 AS builder

WORKDIR /src
COPY go.mod go.sum .
RUN go mod tidy && go mod download
COPY . .
# TODO: replace with >> RUN go test ./... && go build -o server ./cmd/server/main.go
RUN go build -o server ./cmd/server/main.go

FROM alpine:3.22

WORKDIR /app
COPY --from=builder /src/server .

EXPOSE 9999

ENTRYPOINT ["./server"]
